
export const CREATE_CREDIT_CARD_ORDER_ERROR = 'CREATE_CREDIT_CARD_ORDER_ERROR';
export const CREATE_CREDIT_CARD_ORDER_FETCH = 'CREATE_CREDIT_CARD_ORDER_FETCH';
export const CREATE_CREDIT_CARD_ORDER_DATA = 'CREATE_CREDIT_CARD_ORDER_DATA';
